//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeto_pio {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class logado {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal logado() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("projeto_pio.logado", typeof(logado).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool bairro_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("bairro_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button1_Image {
            get {
                object obj = ResourceManager.GetObject("button1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button2_Image {
            get {
                object obj = ResourceManager.GetObject("button2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button3_Image {
            get {
                object obj = ResourceManager.GetObject("button3.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button4_Image {
            get {
                object obj = ResourceManager.GetObject("button4.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool celular_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("celular_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool cpf_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("cpf_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool email_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("email_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool endereco_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("endereco_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool nome_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("nome_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool numero_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("numero_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool rg_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("rg_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool senha_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("senha_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Boolean semelhante a True.
        /// </summary>
        internal static bool Tel_grid_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Tel_grid.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
